export const shipmentsArray = [
  {
    Id: 23,
    SenderId: 3,
    ReceiverId: 4,
    ShipmentReference: "Shipment101",
    ShipmentDescription: "test desc",
    PONumber: "po101",
    NotRequiredForOrder: false,
    ShipmentNumber: null,
    TemperatureRequirements: "Frozen",
    TemperatureRequirementsCelcius: "-20°C",
    PackageDetails: [
      {
        Id: 21,
        PackageType: "",
        Quantity: 0,
        Width: 0,
        Height: 0,
        Length: 0,
        Weight: 0,
      },
    ],
    DomesticSameDay: false,
    DomesticOvernight: false,
    TemperatureControlledVehicle: false,
    AdditionalDeliveryInfo: "add info",
    PickUpDateFrom: "2023-08-21T08:00:00",
    PickUpDateTo: "2023-08-21T12:00:00",
    DeliveryDateFrom: "2023-08-22T08:00:00",
    DeliveryDateTo: "2023-08-22T12:00:00",
    CreateTime: "2023-08-16T16:14:32.237",
    CreatedBy: "lclyde@cenglobal.com",
    PickupDetails: {
      Id: 3,
      OrgCode: "CENGLOBHX",
      Address1: "UNIT, 14A ALDRIDGE ROAD, TAMEBRIDGE INDUSTRIAL EST",
      Address2: "PERRY BARR",
      UNLOCO: "GBBHM",
      BuildingName: "OSMA",
      Country: "GB",
      Postcode: "B42 2TX",
      CompanyName: "CenGlobal",
      ContactName: "Clyde Lester Trinidad",
      ContactNumber: "+63980 141 1717",
      ContactEmail: "lclyde@cenglobal.com",
      AdditionalDetails: null,
    },
    DeliveryDetails: {
      Id: 4,
      OrgCode: "ATMINT_AE",
      Address1: "JEBEL ALI FREE ZONE",
      Address2: "LOB 20 , F07",
      UNLOCO: "AEJEA",
      BuildingName: "OSMA",
      Country: "AE",
      Postcode: "00123",
      CompanyName: "ATMS & INTERNATIONAL FZCO",
      ContactName: "Shazeem Bin Salam",
      ContactNumber: "12345678",
      ContactEmail: "sbinsalam@cenglobal.com",
      AdditionalDetails: null,
    },
  },
  {
    Id: 24,
    SenderId: 4,
    ReceiverId: 3,
    ShipmentReference: "Shipment102",
    ShipmentDescription: "test desc",
    PONumber: "po102",
    NotRequiredForOrder: false,
    ShipmentNumber: null,
    TemperatureRequirements: "Controlled ambient",
    TemperatureRequirementsCelcius: "15°C - 25°",
    PackageDetails: [
      {
        Id: 22,
        PackageType: "",
        Quantity: 0,
        Width: 0,
        Height: 0,
        Length: 0,
        Weight: 0,
      },
    ],
    DomesticSameDay: true,
    DomesticOvernight: false,
    TemperatureControlledVehicle: false,
    AdditionalDeliveryInfo: "add info",
    PickUpDateFrom: "2023-08-18T00:00:00",
    PickUpDateTo: "2023-08-18T00:00:00",
    DeliveryDateFrom: "2023-08-18T00:00:00",
    DeliveryDateTo: "2023-08-18T00:00:00",
    CreateTime: "2023-08-16T16:15:43.5",
    CreatedBy: "lclyde@cenglobal.com",
    PickupDetails: {
      Id: 4,
      OrgCode: "ATMINT_AE",
      Address1: "JEBEL ALI FREE ZONE",
      Address2: "LOB 20 , F07",
      UNLOCO: "AEJEA",
      BuildingName: "OSMA",
      Country: "AE",
      Postcode: "00123",
      CompanyName: "ATMS & INTERNATIONAL FZCO",
      ContactName: "Shazeem Bin Salam",
      ContactNumber: "12345678",
      ContactEmail: "sbinsalam@cenglobal.com",
      AdditionalDetails: null,
    },
    DeliveryDetails: {
      Id: 3,
      OrgCode: "CENGLOBHX",
      Address1: "UNIT, 14A ALDRIDGE ROAD, TAMEBRIDGE INDUSTRIAL EST",
      Address2: "PERRY BARR",
      UNLOCO: "GBBHM",
      BuildingName: "OSMA",
      Country: "GB",
      Postcode: "B42 2TX",
      CompanyName: "CenGlobal",
      ContactName: "Clyde Lester Trinidad",
      ContactNumber: "+63980 141 1717",
      ContactEmail: "lclyde@cenglobal.com",
      AdditionalDetails: null,
    },
  },
  {
    Id: 25,
    SenderId: 3,
    ReceiverId: 4,
    ShipmentReference: "Shipment103",
    ShipmentDescription: "Test desc",
    PONumber: "po103",
    NotRequiredForOrder: false,
    ShipmentNumber: null,
    TemperatureRequirements: "Frozen",
    TemperatureRequirementsCelcius: "-20°C",
    PackageDetails: [
      {
        Id: 23,
        PackageType: "",
        Quantity: 0,
        Width: 0,
        Height: 0,
        Length: 0,
        Weight: 0,
      },
    ],
    DomesticSameDay: false,
    DomesticOvernight: false,
    TemperatureControlledVehicle: false,
    AdditionalDeliveryInfo: "add info",
    PickUpDateFrom: "2023-08-22T12:00:00",
    PickUpDateTo: "2023-08-22T17:00:00",
    DeliveryDateFrom: "2023-08-23T12:00:00",
    DeliveryDateTo: "2023-08-23T17:00:00",
    CreateTime: "2023-08-16T19:24:39.643",
    CreatedBy: "lclyde@cenglobal.com",
    PickupDetails: {
      Id: 3,
      OrgCode: "CENGLOBHX",
      Address1: "UNIT, 14A ALDRIDGE ROAD, TAMEBRIDGE INDUSTRIAL EST",
      Address2: "PERRY BARR",
      UNLOCO: "GBBHM",
      BuildingName: "OSMA",
      Country: "GB",
      Postcode: "B42 2TX",
      CompanyName: "CenGlobal",
      ContactName: "Clyde Lester Trinidad",
      ContactNumber: "+63980 141 1717",
      ContactEmail: "lclyde@cenglobal.com",
      AdditionalDetails: null,
    },
    DeliveryDetails: {
      Id: 4,
      OrgCode: "ATMINT_AE",
      Address1: "JEBEL ALI FREE ZONE",
      Address2: "LOB 20 , F07",
      UNLOCO: "AEJEA",
      BuildingName: "OSMA",
      Country: "AE",
      Postcode: "00123",
      CompanyName: "ATMS & INTERNATIONAL FZCO",
      ContactName: "Shazeem Bin Salam",
      ContactNumber: "12345678",
      ContactEmail: "sbinsalam@cenglobal.com",
      AdditionalDetails: null,
    },
  },
  {
    Id: 27,
    SenderId: 3,
    ReceiverId: 4,
    ShipmentReference: "Shipment104",
    ShipmentDescription: "testdesc",
    PONumber: "po104",
    NotRequiredForOrder: false,
    ShipmentNumber: "SCGBO00001085",
    TemperatureRequirements: "Frozen",
    TemperatureRequirementsCelcius: "-20°C",
    PackageDetails: [
      {
        Id: 25,
        PackageType: "PLT",
        Quantity: 1,
        Width: 200,
        Height: 400,
        Length: 300,
        Weight: 85,
      },
    ],
    DomesticSameDay: false,
    DomesticOvernight: false,
    TemperatureControlledVehicle: false,
    AdditionalDeliveryInfo: "add info",
    PickUpDateFrom: "2023-08-22T12:00:00",
    PickUpDateTo: "2023-08-22T17:00:00",
    DeliveryDateFrom: "2023-08-23T12:00:00",
    DeliveryDateTo: "2023-08-23T17:00:00",
    CreateTime: "2023-08-18T20:42:45.403",
    CreatedBy: "lclyde@cenglobal.com",
    PickupDetails: {
      Id: 3,
      OrgCode: "CENGLOBHX",
      Address1: "UNIT, 14A ALDRIDGE ROAD, TAMEBRIDGE INDUSTRIAL EST",
      Address2: "PERRY BARR",
      UNLOCO: "GBBHM",
      BuildingName: "OSMA",
      Country: "GB",
      Postcode: "B42 2TX",
      CompanyName: "CenGlobal",
      ContactName: "Clyde Lester Trinidad",
      ContactNumber: "+63980 141 1717",
      ContactEmail: "lclyde@cenglobal.com",
      AdditionalDetails: null,
    },
    DeliveryDetails: {
      Id: 4,
      OrgCode: "ATMINT_AE",
      Address1: "JEBEL ALI FREE ZONE",
      Address2: "LOB 20 , F07",
      UNLOCO: "AEJEA",
      BuildingName: "OSMA",
      Country: "AE",
      Postcode: "00123",
      CompanyName: "ATMS & INTERNATIONAL FZCO",
      ContactName: "Shazeem Bin Salam",
      ContactNumber: "12345678",
      ContactEmail: "sbinsalam@cenglobal.com",
      AdditionalDetails: null,
    },
  },
];
